name: alchemist_arsenal
description: "Project for my brother inventory"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  provider: ^6.1.5+1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.28.1
  build_runner: ^2.6.0

flutter:
  uses-material-design: true
